name: Coverage

on:
  - pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: netkan
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install test dependencies
        run: pip install .[test]
      - name: force our git config
        run: cp .gitconfig ~/.
      - name: Run Coverage
        run: coverage run -m pytest
      - name: Generate report
        run: coverage xml
      - name: Get Cover
        uses: orgoro/coverage@v3
        with:
          coverageFile: netkan/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
