name: unittest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: unittest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        pyhon-version: 3.7
    - name: Install Dependencies
      run: |
        pip install netkan/.[test]
    - name: Run unittest
      working-directory: ./netkan
      run: |
        python -m unittest -v
